/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 음성 대화 (STT → LLM → TTS 통합 파이프라인)
         * @description 아이의 음성을 올리면 서버가 STT → LLM → TTS를 한 번에 처리하고
         *     텍스트와 음성(base64 mp3)을 함께 돌려준다. 왕복 1회로 지연 최소화.
         *
         *     **설계 계약**
         *     - STT가 못 알아들어도 `200`이다. `userText: null` + 되묻기 `aiText`가 온다.
         *     - 응답을 받은 앱은 `history`에 user/assistant 두 턴을 추가한다 (`userText`가 null이면 user 턴 생략).
         *     - 오디오 원본은 저장하지 않는다. 응답 헤더 `X-Audio-Retention: none`.
         *     - `aiText`는 한국어교육과정 1~2급 어휘로 생성된다 (FastAPI 프롬프트 담당).
         *     - 타임아웃: Gateway → FastAPI 30초 (3단 파이프라인이라 다른 엔드포인트보다 길다).
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/stt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 음성 → 텍스트
         * @description 음성만 텍스트로 바꾼다. SPEAK/SHADOW 스텝처럼 LLM 응답이 필요 없는 화면에서 쓴다.
         *     인식 결과와 목표 문장의 매칭 판정은 앱 로컬에서 한다.
         *
         *     **인식 실패는 에러가 아니다** — `text: null`로 `200`이 내려간다.
         *     `422 STT_FAILED`는 STT 엔진 자체가 죽었을 때만 쓴다.
         */
        post: operations["stt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 텍스트 → 음성
         * @description 텍스트를 음성(base64 mp3)으로 바꾼다. DIALOGUE 🔊 버튼, LISTEN 스텝에서 쓴다.
         *
         *     - `voice`는 OpenAI 보이스 ID가 아니라 역할 enum이다. 실제 보이스 매핑은 FastAPI 설정에 둔다.
         *     - 같은 문장의 TTS 결과는 앱이 로컬 캐시한다 — 매번 서버에 묻지 않는다.
         */
        post: operations["tts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 발화 피드백 생성
         * @description 아이의 발화(STT 결과 텍스트)와 목표 문장을 주면 FEEDBACK 스텝에 그릴 피드백 객체를 생성한다.
         *     음성이 아니라 텍스트를 받는다 — STT는 `/ai/stt`에서 이미 끝났다.
         *
         *     **설계 계약**
         *     - `recognizedText: null`도 유효한 요청이다 → 격려 피드백을 만든다.
         *     - `reaction`·`comment`에 "틀렸어요"류 문구 금지.
         *     - 번역을 함께 내려보낸다 — 앱이 `/translate`를 따로 부르면 화면이 두 번 늦게 뜬다.
         *     - 발화 기록은 서버에 남지 않는다.
         *     - **부르는 앱 화면이 아직 없다.** 게이트웨이·FastAPI 에는 살아 있다.
         */
        post: operations["feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/pronunciation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 발음 채점
         * @description 따라 말한 녹음의 발음을 채점한다. 발음 피드백 화면(빈칸 퀴즈)에서 쓴다.
         *
         *     - `/ai/feedback`과 다르다. 저쪽은 "어떤 단어를 골랐나"를 텍스트로 보고,
         *       이쪽은 "어떻게 소리 냈나"를 오디오로 본다. 그래서 STT를 거치지 않는다.
         *     - `sentenceId`는 자유 텍스트가 아니다. `GET /ai/pronunciation/sentences`가
         *       내려준 10개 중 하나를 그대로 돌려보내야 한다. FastAPI가 자기 목록에서
         *       채점 기준 문장을 직접 찾기 때문이다 (2026-08-24 FastAPI 명세 변경).
         *     - 점수는 0~1이 아니라 z점수다. 또래 규준 대비 상대값이라 음수가 정상이며,
         *       화면에 숫자를 표시하지 않는다.
         *     - **잘함/못함 판정은 FastAPI가 한다.** `targetWord`가 `null`이면 발음이
         *       전부 기준(z ≥ -1.5) 이상이라는 뜻이다 — 퀴즈 화면 없이 바로 칭찬 화면으로 간다.
         *     - 빈칸은 `targetWord` 하나뿐이다. 화면의 빈칸 문장은 앱이 `sentence`와
         *       `targetIndex`로 직접 만든다 — 서버는 만들어주지 않는다.
         */
        post: operations["pronunciation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/pronunciation/sentences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 발음 연습 문장 목록
         * @description 발음 연습용 문장 21개를 돌려준다 — 등교 9 · 수업시간 동시 3 · 급식 3 · 하교 6.
         *     개수는 카테고리마다 다르고 콘텐츠라 앞으로도 늘어난다. 숫자로 못박지 마라.
         *     "표현 고르기" 화면의 선택지 3개, 수업시간 "같이 읽어볼까요?"의 시 구절이
         *     모두 여기서 온다 — 앱 번들 데이터가 아니다
         *     (2026-08-24부터. 이전에는 시나리오별로 앱에 하드코딩돼 있었다).
         *
         *     `category`로 필터링한 뒤 **무작위 3개만** 화면에 띄운다 — 아홉 개를 한 번에
         *     보여주면 아이가 고르지 못하고 헤맨다. 뽑기는 앱이 하고, 서버는 누가 불러도
         *     같은 목록을 준다.
         *     고른 문장의 `sentenceId`를 `POST /ai/pronunciation`에 그대로 실어 보낸다.
         */
        get: operations["pronunciationSentences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 동화 생성
         * @description 하루치 플레이 기록 4장면을 받아 LLM이 동화로 엮어 돌려준다.
         *
         *     다른 엔드포인트와 달리 "방금 한 행동"이 아니라 **"오늘 한 일 전부"** 를 한 번에 보낸다.
         *     그 기록을 모아두는 것은 **앱의 몫**이다 — 서버는 아무것도 저장하지 않는다(무상태).
         *
         *     **타임아웃이 60초다.** 4장면을 한 번에 생성하기 때문이며 다른 엔드포인트(15초)보다
         *     훨씬 길다. 앱은 반드시 로딩 화면을 띄운다.
         *
         *     `category` 값이 `/ai/pronunciation/sentences`와 다르다는 점에 주의한다 —
         *     저쪽은 arrival/study/lunch/departure, 여기는 school_arrival/class/lunch/school_departure다.
         */
        post: operations["story"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 동화 목록 (최신순)
         * @description 표지를 그리는 데 필요한 것만 준다. `categories` 는 목록에서 **보석 줄**을
         *     그리는 데 쓴다 — 글자를 아직 못 읽는 아이도 색이 다른 보석 네 개를 보고
         *     그날을 알아본다.
         */
        get: operations["listAlbums"];
        put?: never;
        /**
         * 동화를 앨범에 남긴다
         * @description 하루를 마치며 만든 동화를 남긴다. 다음 날에도 다시 읽을 수 있게 된다.
         *
         *     **앱은 동화를 화면에 띄운 뒤에 부른다.** 저장을 기다렸다 보여주면 저장이
         *     늦거나 실패하는 날 아이가 동화를 아예 못 본다. 실패해도 화면을 막지 않는다.
         *
         *     **삽화는 보내지 않는다.** 앱 번들의 정적 그림이고 장면의 `category` 하나로
         *     결정된다 — 이미지를 저장하면 동화마다 같은 파일을 복제하면서, 나중에 그림을
         *     고쳐도 옛 앨범만 낡은 그림으로 남는다.
         */
        post: operations["saveAlbum"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 동화 한 편
         * @description 앱이 이걸 받아 동화 화면을 그대로 다시 그린다.
         *
         *     **`childId` 를 반드시 함께 보낸다.** `id` 만으로 찾지 않는 이유는 인증이
         *     없기 때문이다 — 번호를 하나씩 올려보는 것만으로 남의 동화를 읽을 수 있다.
         *
         *     주인이 아닐 때 `403` 이 아니라 `404` 를 준다. `403` 은 "있긴 있다"를
         *     알려주는 셈이라 번호를 훑어 남의 동화가 몇 편인지 셀 수 있다.
         */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description LLM 프롬프트 컨텍스트용 힌트. 앱 로컬의 시나리오 코드와 동일
         * @example LUNCH
         * @enum {string}
         */
        Scenario: "ARRIVAL" | "CLASS" | "LUNCH" | "DISMISSAL";
        /**
         * @description 피드백·번역 생성 언어. KOREAN이면 번역 생략
         * @default KOREAN
         * @example VIETNAMESE
         * @enum {string}
         */
        NativeLanguage: "KOREAN" | "CHINESE" | "VIETNAMESE";
        /** @description 서버 → 앱 오디오. chat과 tts가 동일 구조를 쓴다 — 앱의 재생 코드는 하나면 된다 */
        AudioPayload: {
            /**
             * Format: byte
             * @description base64 인코딩된 mp3 바이너리
             */
            data: string;
            /** @enum {string} */
            format: "mp3";
        };
        ChatResult: {
            /** @description STT 결과. 못 알아들으면 null (에러 아님) */
            userText: string | null;
            /** @description 상대 캐릭터의 답 (한국어교육과정 1~2급 어휘) */
            replyText: string;
            audio?: components["schemas"]["AudioPayload"] | null;
            /** @description 이 턴까지의 대화. 앱이 다음 요청에 그대로 실어 보낸다. */
            history?: {
                /** @enum {string} */
                role: "user" | "assistant";
                content: string;
            }[];
            /** @description 목 제공자가 만든 값이라는 표시. 실제 응답이면 키 자체가 없다. */
            mock?: boolean;
        };
        SttResult: {
            /** @description 인식 결과. 못 알아들으면 null (에러 아님) */
            text: string | null;
            /** @description 엔진이 안 주면 null. 화면 표시 금지 */
            confidence?: number | null;
            /**
             * @description 인식된 언어. 앱 계약 enum 이다(`ko` 가 아니라 `KOREAN`).
             * @default KOREAN
             */
            language: string;
            /**
             * Format: float
             * @default 0
             */
            durationSec: number;
            /** @description 구간별 인식 결과. 지금 앱 화면은 쓰지 않는다. */
            segments?: Record<string, never>[];
        };
        /**
         * @description **표현 교정.** 어떤 낱말을 골랐나를 본다(발음 채점과 다르다).
         *
         *     번역을 여기 합쳐 내려보낸다 — 앱이 `/translate` 를 따로 부르면 같은 화면을
         *     두 번 기다리게 된다.
         */
        FeedbackResult: {
            /**
             * @description 말풍선 — 알아들었다는 반응
             * @example 잘 말했어!
             */
            reaction: string;
            /**
             * @description 안내 카드 문구
             * @example 이렇게 말하면 더 자연스러워요.
             */
            comment: string;
            /**
             * @description 권하는 한국어 문장
             * @example 조금만 주세요.
             */
            naturalSentence: string;
            /** @description 왜 그렇게 말하는지 한 줄 설명 */
            naturalHint: string;
            /** @description naturalSentence 안에서 짚어줄 어절. 없으면 [] */
            highlightWords: string[];
            /** @description 모국어 번역. nativeLanguage 가 KOREAN 이거나 없으면 null */
            translation?: string | null;
            /** @description 번역한 언어(앱 계약 enum). 번역이 없으면 null */
            translationLanguage?: string | null;
        };
        /**
         * Format: uuid
         * @description 기기가 처음 켜질 때 만든 UUIDv4. 로그인이 없으므로 **이것이 "누구인가"의 전부다.**
         *
         *     닉네임을 키로 쓰지 않는 이유는 셋이다 — 겹치고(같은 반에 "지우"가 둘),
         *     바뀌고(메뉴에서 이름 수정), 아이 이름이 모든 조회 주소에 실린다.
         *
         *     앱은 `localStorage['zooearly.childId']` 에 프로필과 **따로** 보관한다.
         *     날짜가 바뀌어 진행도가 비워질 때 앨범까지 잃으면 안 되기 때문이다.
         *     다만 "처음부터 플레이하기"(기기를 다음 아이에게 넘기는 동선)에서는 새로 만든다.
         * @example a355d4f5-f7ac-4b74-8733-b28236b270ac
         */
        ChildId: string;
        AlbumScene: {
            /**
             * @description **삽화를 고르는 유일한 키.** 앱이 이 값으로 번들의 정적 그림을 찾는다.
             *     그래서 이미지를 저장하지 않는다.
             * @enum {string}
             */
            category: "school_arrival" | "class" | "lunch" | "school_departure";
            /** @example 학교 오는 길 */
            subtitle: string;
            /** @example 아침에 */
            opening?: string;
            /**
             * @description 아이가 실제로 고른 말. 화면에 인용 블록으로 뜬다. 고르지 않고 넘어간 장면은 null.
             * @example 안녕! 우리 같이 놀자!
             */
            quote?: string | null;
            /** @example 지우가 학교에 왔어요. */
            narration: string;
        };
        AlbumSaveRequest: {
            childId: components["schemas"]["ChildId"];
            /**
             * @description 만들 때의 이름. **표시용이지 키가 아니다** — 나중에 이름을 바꿔도 옛 표지는 그대로다.
             * @example 지우
             */
            nickname: string;
            /** @example 지우가 들려준 오늘 */
            title: string;
            scenes: components["schemas"]["AlbumScene"][];
        };
        AlbumSummary: {
            /**
             * Format: int64
             * @example 12
             */
            id: number;
            /** @example 지우가 들려준 오늘 */
            title: string;
            /** @example 지우 */
            nickname: string;
            /**
             * Format: date-time
             * @example 2026-08-27T01:10:51.313624Z
             */
            createdAt: string;
            /** @description 목록에서 보석 줄을 그리는 데 쓴다. 장면 순서대로. */
            categories: ("school_arrival" | "class" | "lunch" | "school_departure")[];
        };
        AlbumDetail: {
            /** Format: int64 */
            id: number;
            title: string;
            /** @description 그때 그 이름. 지금 프로필과 다를 수 있다. */
            nickname: string;
            /** Format: date-time */
            createdAt: string;
            scenes: components["schemas"]["AlbumScene"][];
        };
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never>;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                code: "INVALID_PARAMETER" | "UNSUPPORTED_AUDIO_FORMAT" | "AUDIO_TOO_LARGE" | "PAYLOAD_TOO_LARGE" | "STT_FAILED" | "RATE_LIMITED" | "AI_SERVER_ERROR" | "AI_TIMEOUT" | "INTERNAL_ERROR";
                /** @description 개발자용. 아이 화면에 띄우지 않는다 */
                message: string;
                /** @description 문제가 된 파라미터명. 검증 에러에만 채워진다 */
                field?: string | null;
            };
        };
    };
    responses: {
        /** @description 검증 실패 (Gateway) — INVALID_PARAMETER / UNSUPPORTED_AUDIO_FORMAT / AUDIO_TOO_LARGE */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "INVALID_PARAMETER",
                 *         "message": "audio 필드가 없습니다.",
                 *         "field": "audio"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 요청 전체 용량 초과 (Gateway) — PAYLOAD_TOO_LARGE */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "PAYLOAD_TOO_LARGE",
                 *         "message": "요청이 너무 큽니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description STT 엔진 자체 실패 (FastAPI) — 인식 실패(null 반환)와 다르다 */
        SttFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "STT_FAILED",
                 *         "message": "STT 엔진 오류.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 발음 채점이 이 녹음으로는 성립하지 않는다. 두 가지 code 로 온다.
         *
         *     | code | field | 언제 |
         *     |---|---|---|
         *     | `OFF_SCRIPT` | audio | 고른 문장이 아니라 아주 다른 말을 했다 (v2.1.0 신설) |
         *     | `INVALID_PARAMETER` | audio | 녹음이 비었거나 · 20MB 초과 · 채점할 어절이 하나도 없다 |
         *     | `INVALID_PARAMETER` | sentenceId | 문장 미선택 · 목록에 없는 id — 앱의 버그다 |
         *
         *     **STT_FAILED 는 이 경로에 오지 않는다.** 발음 채점은 STT 를 거치지 않고
         *     오디오를 그대로 채점 서비스에 넘긴다. 이전 명세의 오기였다.
         *
         *     **실패가 아니라 되묻기다.** 앱은 이 응답을 받으면 녹음 화면에 그대로
         *     머물면서 "잘 못 들었어. 다시 말해줄래?" 로 되묻고, 다시 녹음할 수 있게
         *     한다. 다른 4xx 와 같이 처리하면 안 된다 — 그러면 아이가 배우는 것이
         *     "아무 말이나 하면 통과한다" 가 된다. (실제로 그랬다: 앱이 채점 실패를
         *     전부 칭찬 화면으로 흘려보내서, 전혀 다른 말을 해도 "잘했어!" 가 떴다.)
         *
         *     같은 422 로 오는 다른 두 경우(채점할 어절이 없음 · 녹음이 비었음)도
         *     아이 입장에서는 같은 일이라 같이 다룬다. 앱은 코드가 아니라 **422 인지**를
         *     본다 — 코드로만 가르면 서버가 코드를 하나 더 늘리는 날 조용히 칭찬
         *     화면으로 새는 길이 생긴다.
         *
         *     세 번까지 되묻고, 그 뒤에는 넘어갈 길을 연다(그 길도 칭찬 화면은 아니다).
         */
        PronunciationUnprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description OpenAI API 쿼터 초과 (FastAPI) — RATE_LIMITED */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "요청이 너무 많습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description FastAPI 5xx 또는 연결 불가 (Gateway 변환) — AI_SERVER_ERROR */
        AiServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "AI_SERVER_ERROR",
                 *         "message": "추론 서버가 응답하지 않습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 타임아웃 초과 (Gateway) — tts·문장목록 15s / feedback·chat 30s / stt 45s / story 60s / pronunciation 65s */
        AiTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "AI_TIMEOUT",
                 *         "message": "추론 시간이 초과되었습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 아이의 발화. m4a/wav/webm, 최대 10MB · 30초
                     */
                    audio: string;
                    scenario: components["schemas"]["Scenario"];
                    /**
                     * @description 지금까지의 대화를 담은 JSON 문자열. 없으면 `"[]"`.
                     *     최근 10턴까지만 보낸다 (앱이 자른다).
                     *     형식: `[{"role":"user"|"assistant","content":"..."}]`
                     * @example [{"role":"assistant","content":"불고기 많이 줄까?"}]
                     */
                    history: string;
                    nativeLanguage?: components["schemas"]["NativeLanguage"];
                    /**
                     * @description 아이 호칭. 앱 온보딩에서 받은 값. 서버는 저장하지 않는다
                     * @example 민수
                     */
                    nickname: string;
                };
            };
        };
        responses: {
            /** @description 대화 성공 (STT 인식 실패 포함 — userText가 null일 뿐 에러가 아니다) */
            200: {
                headers: {
                    /** @description 오디오 원본 미저장 보증 */
                    "X-Audio-Retention"?: "none";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "userText": "네, 많이 주세요.",
                     *         "aiText": "그래, 많이 줄게! 맛있게 먹어.",
                     *         "audio": {
                     *           "data": "SUQzBAAA...",
                     *           "format": "mp3"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ChatResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["SttFailed"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    stt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description m4a/wav/webm, 최대 10MB · 30초
                     */
                    audio: string;
                    /**
                     * @description BCP-47 언어 코드
                     * @default ko-KR
                     */
                    language?: string;
                };
            };
        };
        responses: {
            /** @description 변환 성공 (인식 실패 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "text": "많이 주세요",
                     *         "confidence": 0.94
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["SttResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["SttFailed"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    tts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 읽을 문장
                     * @example 불고기 많이 줄까?
                     */
                    text: string;
                    /**
                     * @description 역할 enum. 실제 보이스 매핑은 FastAPI 담당
                     * @default TEACHER
                     * @enum {string}
                     */
                    voice?: "TEACHER" | "FRIEND";
                    /**
                     * @description 재생 속도. 아동용 기본 느리게
                     * @default 0.9
                     */
                    speed?: number;
                    /**
                     * @description 읽을 문장의 언어. 필수.
                     *     한국어 문장을 읽을 때도 KOREAN을 명시한다. 같은 엔드포인트로
                     *     여러 언어가 나가므로 추측의 여지를 두지 않는다.
                     *     주의: /ai/stt의 language는 BCP-47 문자열이고 이쪽은 enum이다.
                     */
                    language: components["schemas"]["NativeLanguage"];
                };
            };
        };
        responses: {
            /** @description 합성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "audio": {
                     *           "data": "SUQzBAAA...",
                     *           "format": "mp3"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            audio: components["schemas"]["AudioPayload"];
                            /**
                             * @description 목 제공자가 만든 차임이라는 표시. **실제 음성이면 키 자체가 없다.**
                             *     앱은 이 값을 보고 브라우저 음성합성으로 대신 읽어줄지 정한다.
                             */
                            mock?: boolean;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    feedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 목표 문장 (앱 번들의 스텝 데이터)
                     * @example 많이 주세요.
                     */
                    targetSentence: string;
                    /**
                     * @description STT 결과. 인식 실패면 null
                     * @example 많이 주세여
                     */
                    recognizedText: string | null;
                    scenario?: components["schemas"]["Scenario"];
                    nativeLanguage?: components["schemas"]["NativeLanguage"];
                    /**
                     * @description 아이 호칭. 앱 온보딩에서 받은 값. 서버는 저장하지 않는다
                     * @example 민수
                     */
                    nickname: string;
                };
            };
        };
        responses: {
            /** @description 피드백 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "reaction": "무슨 뜻인지 잘 알겠어!",
                     *         "comment": "이렇게 말하면 더 자연스러워요.",
                     *         "naturalSentence": "많이 주세요.",
                     *         "naturalHint": "'주세여'보다 '주세요'가 좋아요.",
                     *         "highlightWords": [
                     *           "주세요"
                     *         ],
                     *         "translation": "Cho mình nhiều nhé.",
                     *         "translationLanguage": "VIETNAMESE"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["FeedbackResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    pronunciation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 따라 말한 녹음. m4a/wav/webm, 최대 10MB · 30초
                     */
                    audio: string;
                    /**
                     * @description `GET /ai/pronunciation/sentences`에서 받은 값 중 하나.
                     *     앱이 직접 만들지 않는다 — 서버 목록에 없는 값은 422가 난다.
                     * @example arrival_2
                     */
                    sentenceId: string;
                };
            };
        };
        responses: {
            /** @description 채점 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "sentenceId": "arrival_2",
                     *         "sentence": "안녕! 우리 같이 놀자!",
                     *         "targetWord": "지내자",
                     *         "targetIndex": 2,
                     *         "targetZ": -1.82,
                     *         "words": [
                     *           {
                     *             "word": "안녕!",
                     *             "z": 0.31,
                     *             "warn": false,
                     *             "worstPhone": null
                     *           },
                     *           {
                     *             "word": "우리",
                     *             "z": -0.42,
                     *             "warn": false,
                     *             "worstPhone": null
                     *           },
                     *           {
                     *             "word": "친하게",
                     *             "z": -1.12,
                     *             "warn": false,
                     *             "worstPhone": null
                     *           },
                     *           {
                     *             "word": "지내자",
                     *             "z": -1.82,
                     *             "warn": true,
                     *             "worstPhone": "ㄴ"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            /** @description 요청에 실은 값을 그대로 돌려준다 */
                            sentenceId?: string;
                            /** @description 채점 대상 문장 */
                            sentence?: string;
                            /**
                             * @description 가장 약하게 발음한 어절. 빈칸으로 만들 대상.
                             *     null이면 전부 기준 이상이라는 뜻 — 퀴즈 화면 없이
                             *     바로 칭찬 화면으로 간다.
                             * @example 지내자
                             */
                            targetWord?: string | null;
                            /** @description 그 어절이 몇 번째인가 (0부터) */
                            targetIndex?: number | null;
                            /** @description 그 어절의 z점수. 낮을수록 약하다 */
                            targetZ?: number | null;
                            /** @description 어절별 채점 결과 */
                            words?: {
                                word?: string;
                                z?: number | null;
                                /** @description 주의 임계값 미만인가 */
                                warn?: boolean;
                                worstPhone?: string | null;
                            }[];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["PronunciationUnprocessable"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    pronunciationSentences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": [
                     *         {
                     *           "sentenceId": "arrival_1",
                     *           "category": "arrival",
                     *           "text": "안녕 나도 만나서 반가워 !",
                     *           "translations": {
                     *             "vi": "Chào cậu! Mình cũng rất vui được gặp cậu!",
                     *             "zh": "你好！我也很高兴见到你！"
                     *           }
                     *         },
                     *         {
                     *           "sentenceId": "arrival_2",
                     *           "category": "arrival",
                     *           "text": "안녕! 우리 같이 놀자!"
                     *         },
                     *         {
                     *           "sentenceId": "arrival_3",
                     *           "category": "arrival",
                     *           "text": "안녕! 같이 들어가자!"
                     *         },
                     *         {
                     *           "sentenceId": "study_1",
                     *           "category": "study",
                     *           "text": "노란 꽃이 피었어요. 예쁜 꽃이 피었어요. 바람이 살랑살랑 꽃이 웃어요."
                     *         },
                     *         {
                     *           "sentenceId": "lunch_1",
                     *           "category": "lunch",
                     *           "text": "조금만 주세요."
                     *         },
                     *         {
                     *           "sentenceId": "lunch_2",
                     *           "category": "lunch",
                     *           "text": "적당히 주세요."
                     *         },
                     *         {
                     *           "sentenceId": "lunch_3",
                     *           "category": "lunch",
                     *           "text": "많이 주세요."
                     *         },
                     *         {
                     *           "sentenceId": "departure_1",
                     *           "category": "departure",
                     *           "text": "선생님, 안녕히 가세요!"
                     *         },
                     *         {
                     *           "sentenceId": "departure_2",
                     *           "category": "departure",
                     *           "text": "선생님, 감사합니다!"
                     *         },
                     *         {
                     *           "sentenceId": "departure_3",
                     *           "category": "departure",
                     *           "text": "내일 또 뵙겠습니다!"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            /** @description 발음 채점 요청에 그대로 실어 보내는 값 */
                            sentenceId?: string;
                            /**
                             * @description 등교/수업시간/급식/하교 구분. 소문자이고 §1.5의 Scenario enum
                             *     (ARRIVAL/CLASS/LUNCH/DISMISSAL, 대문자)과 표기가 다르다 —
                             *     이 API 전용 값이니 섞어 쓰지 않는다.
                             *     개수는 카테고리마다 다르다(arrival 9 · study 3 · lunch 3 ·
                             *     departure 6). study 한 항목은 문장 하나가 아니라 동시 한 편
                             *     전체가 이어져 있다.
                             * @enum {string}
                             */
                            category?: "arrival" | "study" | "lunch" | "departure";
                            /** @description 화면에 보여줄 문장 원문 */
                            text?: string;
                            /**
                             * @description (v2.1.0 신설) 이 문장의 모국어 뜻. 키는 언어 코드
                             *     (vi=베트남어, zh=중국어), 값은 번역문이다. 한국어는 키가
                             *     없다 — 원문이 곧 그것이다.
                             *
                             *     앱의 힌트 전구(💡)가 이 값만 본다. 번역을 따로 부르는
                             *     요청은 없다 — 문장이 10개로 고정이라 목록에 함께 담는
                             *     편이 맞다. 누를 때마다 부르면 아이가 전구를 누르고 몇 초를
                             *     기다려야 하고, 그 사이 자기가 무엇을 물었는지를 잊는다.
                             *
                             *     비어 있을 수 있다고 보고 짜야 한다({}). 앱은 그때 전구를
                             *     아예 보여주지 않는다 — 눌러도 아무 일이 없는 버튼이 화면에
                             *     있는 것이 제일 나쁘다.
                             * @example {
                             *       "vi": "Chào cậu! Chúng mình cùng chơi nhé!",
                             *       "zh": "你好！我们一起玩吧！"
                             *     }
                             */
                            translations?: {
                                [key: string]: string;
                            };
                            /**
                             * @description (v2.2.0 신설) 번역문의 어느 조각이 한국어 어느 어절인지.
                             *     빈칸 퀴즈에서 비운 어절이 모국어 문장의 어디인지 짚어준다.
                             *
                             *     조각은 **번역문을 읽는 순서**대로다 — 한국어 순서가 아니라
                             *     k 가 뒤죽박죽인 것이 정상이다. 한 조각이 어절 여럿을 덮을 수
                             *     있다(굳은 인사는 쪼개면 뜻이 어긋난다).
                             *
                             *     조각을 이으면 translations 와 글자 하나까지 같다
                             *     (vi 는 공백 한 칸, zh 는 붙여서). 서버 기동 시 검산한다.
                             *
                             *     **비어 있을 수 있다** — 동시(study)는 빈칸 퀴즈를 내지 않아
                             *     {} 다. 그때 앱은 뜻만 통째로 보여준다.
                             * @example {
                             *       "vi": [
                             *         {
                             *           "t": "Cho con",
                             *           "k": [
                             *             1
                             *           ]
                             *         },
                             *         {
                             *           "t": "một chút thôi ạ.",
                             *           "k": [
                             *             0
                             *           ]
                             *         }
                             *       ]
                             *     }
                             */
                            translationParts?: {
                                [key: string]: {
                                    /** @description 번역문 조각 */
                                    t: string;
                                    /**
                                     * @description 이 조각이 대응하는 한국어 어절 인덱스들
                                     *     (text.split(' ') 기준. /pronunciation 의
                                     *     targetIndex 와 같은 눈금이다).
                                     *     대응이 없으면 빈 배열.
                                     */
                                    k: number[];
                                }[];
                            };
                        }[];
                    };
                };
            };
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    story: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "childName": "지우",
                 *       "scenes": [
                 *         {
                 *           "category": "school_arrival",
                 *           "partnerLine": "안녕! 오늘도 만나서 반가워",
                 *           "childSaid": "안녕! 나도 만나서 반가워 !"
                 *         },
                 *         {
                 *           "category": "class",
                 *           "poemText": "노란 꽃이 피었어요. 바람이 살랑살랑 꽃이 웃어요.",
                 *           "practicedWord": "살랑살랑"
                 *         },
                 *         {
                 *           "category": "lunch",
                 *           "partnerLine": "오늘 반찬 맛있게 먹어요",
                 *           "childSaid": null
                 *         },
                 *         {
                 *           "category": "school_departure",
                 *           "partnerLine": "오늘도 수고했어, 내일 봐",
                 *           "childSaid": "선생님, 안녕히 가세요!"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @description 아이 이름. 내레이션에 그대로 쓰인다 */
                    childName: string;
                    /**
                     * @description 정확히 4개. 순서 고정 — school_arrival → class → lunch → school_departure.
                     *     위치와 category 값이 일치해야 한다. 어긋나면 400이다.
                     */
                    scenes: {
                        /** @enum {string} */
                        category: "school_arrival" | "class" | "lunch" | "school_departure";
                        /**
                         * @description 상대방이 아이에게 한 말. 대화 장면(school_arrival/lunch/school_departure)에서는 필수다.
                         *     없으면 LLM이 없는 대사를 지어내야 하므로 400으로 끊는다.
                         */
                        partnerLine?: string;
                        /** @description 아이가 고른 문장. 안 골랐으면 null */
                        childSaid?: string | null;
                        /** @description 아이가 읽은 동시 전문. class 장면에서는 필수다 */
                        poemText?: string;
                        /** @description 발음이 약해 연습한 낱말(/ai/pronunciation의 targetWord) */
                        practicedWord?: string | null;
                    }[];
                };
            };
        };
        responses: {
            /** @description 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "title": "오늘의 학교 동화",
                     *         "scenes": [
                     *           {
                     *             "category": "school_arrival",
                     *             "subtitle": "첫 만남의 아침",
                     *             "opening": "교문 앞이었어요",
                     *             "quote": "안녕! 나도 반가워",
                     *             "narration": "지우가 교문 앞에 서 있었어요. 친구가 밝게 인사했지요."
                     *           },
                     *           {
                     *             "category": "class",
                     *             "subtitle": "시를 읽은 시간",
                     *             "opening": "교실 문을 열자",
                     *             "quote": null,
                     *             "narration": "지우가 조용히 교실에 들어갔어요. 노란 꽃 이야기를 읽었답니다."
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            /** @description 동화 제목 */
                            title: string;
                            /** @description 요청과 같은 개수·순서·카테고리 */
                            scenes: {
                                /** @enum {string} */
                                category?: "school_arrival" | "class" | "lunch" | "school_departure";
                                /** @description 장면 소제목 */
                                subtitle?: string;
                                /** @description 장면을 여는 전환구 */
                                opening?: string;
                                /** @description 아이가 한 말 인용. 없으면 null */
                                quote?: string | null;
                                /** @description 동화 문장 2~3문장 */
                                narration?: string;
                            }[];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    listAlbums: {
        parameters: {
            query: {
                childId: components["schemas"]["ChildId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["AlbumSummary"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    saveAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumSaveRequest"];
            };
        };
        responses: {
            /** @description 저장됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            /**
                             * Format: int64
                             * @example 12
                             */
                            id: number;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAlbum: {
        parameters: {
            query: {
                childId: components["schemas"]["ChildId"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 동화 한 편 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["AlbumDetail"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 없거나 내 것이 아니다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
